- hosts: digital_ocean
  accelerate: false
  vars:
    # Core settings
    - maintainer_email: marazmiki@gmail.com
    - maintainer_name: Mikhail Porokhovnichenko
    - user: nopox
    - homedir: "/home/{{ user }}"
    - project_app: project
    - project_root: "{{ homedir }}/{{ project_app }}"
    - project_repo_url: "https://github.com/marazmiki/django-comments-threaded"
    - project_repo_branch: "master"
    - virtualenv_name: "{{ project_root }}/.virtualenv"
    - requirements_file: "{{ project_root }}/requirements-dev.txt"

    # Postgres role settings
    - postgres_host: 127.0.0.1
    - postgres_port: 5432
    - postgres_name: pg_database
    - postgres_user: postgres_user
    - postgres_password: postgres_password

    #  RabbitMQ settings
    - rabbitmq_host: '127.0.0.1'
    - rabbitmq_port: 5672
    - rabbitmq_user: rabbitmq_user
    - rabbitmq_pass: rabbitmq_password

    # Redis settings
    - redis_host: 127.0.0.1
    - redis_port: 6379
    - redis_db: 0

    # Memcache settings
    - memcache_host: 127.0.0.1
    - memcache_port: 11211

  roles:
    - role: bash
    - role: python_dev
    - role: memcached
    - role: redis
    - role: rabbitmq
    - role: postgres
    - role: email
    - role: django
