- name: Install PostgreSQL if this wasn't earlier
  apt: name={{ item }}
  sudo: yes
  with_items:
    - postgresql
    - python-psycopg2
    - libpq-dev

- name: Ensure postgres database {{ postgres_name }} is exists
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ postgres_name }} template=template0 encoding="UTF_8"

- name: Create postgresql user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{ postgres_name }} name={{ postgres_user }} password={{ postgres_password }} priv=ALL
