- name: Install PostgreSQL if this wasn't earlier
  apt: name={{ item }}
  sudo: yes
  with_items:
    - postgresql
    - python-psycopg2
    - libpq-dev

- name: Create postgresql user
  sudo: yes
  sudo_user: postgres
  # postgresql_user: db={{ postgres_name }} name={{ postgres_user }} password={{ postgres_password }} priv=ALL
  postgresql_user: user={{ postgres_user }} password={{ postgres_password }} role_attr_flags=LOGIN 

- name: Ensure postgres database {{ postgres_name }} is exists
  sudo: yes
  sudo_user: postgres
  # postgresql_db: name={{ postgres_name }} template=template0 encoding="UTF_8"
  postgresql_db: name={{ postgres_name }} 
                 owner={{ postgres_user }} 
                 encoding='UTF8'
                 lc_collate='ru_RU.UTF-8' 
                 lc_ctype='ru_RU.UTF-8' 
                 template='template0'
                 state=present


